# Generic support for running flatc to generate C++ accessors
# For *.fbs files, generate *_generated.h
$(COMPILING_COMPONENT_PATH)/src/gen/%_generated.h: $(COMPILING_COMPONENT_PATH)/%.fbs
	flatc --cpp -o $(@D) \
		--scoped-enums \
		--gen-mutable \
		--gen-object-api \
		--gen-name-strings \
		--reflect-types \
		--reflect-names \
		$^
