{
  "version": @CONFIG_FIRMWARE_UPDATE_CURRENT_VERSION_NUMBER@,
  "checksum": "@FIRMWARE_UPDATE_LATEST_CHECKSUM@",
  "url": "@CONFIG_FIRMWARE_UPDATE_LATEST_URL@",
  "interval": @CONFIG_FIRMWARE_UPDATE_CHECK_INTERVAL_SECONDS@
}
