{
  "version": @FIRMWARE_UPDATE_CURRENT_VERSION@,
  "checksum": "@FIRMWARE_UPDATE_LATEST_CHECKSUM@",
  "url": "@CONFIG_FIRMWARE_UPDATE_LATEST_URL@",
  "interval": @CONFIG_FIRMWARE_UPDATE_CHECK_INTERVAL_SECONDS@
}
