# Generate secret *.json files from *.json.tpl, via menuconfig values
$(BUILD_DIR_BASE)/secrets/gen/firmware_update_check_request_intent.req.json: $(COMPILING_COMPONENT_PATH)/templates/firmware_update_check_request_intent.req.json.tpl
	sed \
		-e 's#@CONFIG_FIRMWARE_UPDATE_CHECK_URL@#$(call dequote,$(CONFIG_FIRMWARE_UPDATE_CHECK_URL))#' \
		$^ > $@
